import { priceCase } from "./pricing.js";
export const skins = [
  {
    id: "ak-47-redline",
    weapon: "AK-47",
    name: "Redline",
    rarity: "classified",
    image: "/assets/skins/ak-47-redline.webp",
    skinId: "ak-47-redline",
    value: 12349,
    currency: "USD",
    wear: "Minimal Wear",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Redline (Minimal Wear)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/ak-47-redline",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "MW",
  },
  {
    id: "ak-47-asiimov",
    weapon: "AK-47",
    name: "Asiimov",
    rarity: "covert",
    image: "/assets/skins/ak-47-asiimov.webp",
    skinId: "ak-47-asiimov",
    value: 28947,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Asiimov (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/ak-47-asiimov",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-neon-rider",
    weapon: "AK-47",
    name: "Neon Rider",
    rarity: "covert",
    image: "/assets/skins/ak-47-neon-rider.webp",
    skinId: "ak-47-neon-rider",
    value: 19329,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Neon Rider (Factory New)",
    marketplace: "Skins.com",
    priceSource: "https://csgoskins.gg/items/ak-47-neon-rider",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-fire-serpent",
    weapon: "AK-47",
    name: "Fire Serpent",
    rarity: "covert",
    image: "/assets/skins/ak-47-fire-serpent.webp",
    skinId: "ak-47-fire-serpent",
    value: 210464,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Fire Serpent (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/ak-47-fire-serpent",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-slate",
    weapon: "AK-47",
    name: "Slate",
    rarity: "restricted",
    image: "/assets/skins/ak-47-slate.webp",
    skinId: "ak-47-slate",
    value: 1310,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Slate (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/ak-47-slate",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-elite-build",
    weapon: "AK-47",
    name: "Elite Build",
    rarity: "milspec",
    image: "/assets/skins/ak-47-elite-build.webp",
    skinId: "ak-47-elite-build",
    value: 716,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Elite Build (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/ak-47-elite-build",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-phantom-disruptor",
    weapon: "AK-47",
    name: "Phantom Disruptor",
    rarity: "classified",
    image: "/assets/skins/ak-47-phantom-disruptor.webp",
    skinId: "ak-47-phantom-disruptor",
    value: 1826,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Phantom Disruptor (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/ak-47-phantom-disruptor",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a4-howl",
    weapon: "M4A4",
    name: "Howl",
    rarity: "contraband",
    image: "/assets/skins/m4a4-howl.webp",
    skinId: "m4a4-howl",
    value: 659075,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Howl (Factory New)",
    marketplace: "Skinport",
    priceSource: "https://csgoskins.gg/items/m4a4-howl",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a4-evil-daimyo",
    weapon: "M4A4",
    name: "Evil Daimyo",
    rarity: "restricted",
    image: "/assets/skins/m4a4-evil-daimyo.webp",
    skinId: "m4a4-evil-daimyo",
    value: 751,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Evil Daimyo (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/m4a4-evil-daimyo",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a4-magnesium",
    weapon: "M4A4",
    name: "Magnesium",
    rarity: "milspec",
    image: "/assets/skins/m4a4-magnesium.webp",
    skinId: "m4a4-magnesium",
    value: 512,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Magnesium (Factory New)",
    marketplace: "UUSKINS",
    priceSource: "https://csgoskins.gg/items/m4a4-magnesium",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a1-s-hyper-beast",
    weapon: "M4A1-S",
    name: "Hyper Beast",
    rarity: "covert",
    image: "/assets/skins/m4a1-s-hyper-beast.webp",
    skinId: "m4a1-s-hyper-beast",
    value: 26118,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Hyper Beast (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a1-s-hyper-beast",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a1-s-decimator",
    weapon: "M4A1-S",
    name: "Decimator",
    rarity: "classified",
    image: "/assets/skins/m4a1-s-decimator.webp",
    skinId: "m4a1-s-decimator",
    value: 3898,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Decimator (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/m4a1-s-decimator",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "awp-asiimov",
    weapon: "AWP",
    name: "Asiimov",
    rarity: "covert",
    image: "/assets/skins/awp-asiimov.webp",
    skinId: "awp-asiimov",
    value: 9873,
    currency: "USD",
    wear: "Field-Tested",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Asiimov (Field-Tested)",
    marketplace: "Aim.market",
    priceSource: "https://csgoskins.gg/items/awp-asiimov",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FT",
  },
  {
    id: "awp-hyper-beast",
    weapon: "AWP",
    name: "Hyper Beast",
    rarity: "covert",
    image: "/assets/skins/awp-hyper-beast.webp",
    skinId: "awp-hyper-beast",
    value: 14404,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Hyper Beast (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/awp-hyper-beast",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "awp-dragon-lore",
    weapon: "AWP",
    name: "Dragon Lore",
    rarity: "covert",
    image: "/assets/skins/awp-dragon-lore.webp",
    skinId: "awp-dragon-lore",
    value: 1085304,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Dragon Lore (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/awp-dragon-lore",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "awp-containment-breach",
    weapon: "AWP",
    name: "Containment Breach",
    rarity: "covert",
    image: "/assets/skins/awp-containment-breach.webp",
    skinId: "awp-containment-breach",
    value: 37122,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Containment Breach (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/awp-containment-breach",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "awp-atheris",
    weapon: "AWP",
    name: "Atheris",
    rarity: "restricted",
    image: "/assets/skins/awp-atheris.webp",
    skinId: "awp-atheris",
    value: 2512,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Atheris (Factory New)",
    marketplace: "SkinsMonkey",
    priceSource: "https://csgoskins.gg/items/awp-atheris",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ssg-08-abyss",
    weapon: "SSG 08",
    name: "Abyss",
    rarity: "milspec",
    image: "/assets/skins/ssg-08-abyss.webp",
    skinId: "ssg-08-abyss",
    value: 383,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "SSG 08 | Abyss (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/ssg-08-abyss",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "desert-eagle-blaze",
    weapon: "Desert Eagle",
    name: "Blaze",
    rarity: "restricted",
    image: "/assets/skins/desert-eagle-blaze.webp",
    skinId: "desert-eagle-blaze",
    value: 57500,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Desert Eagle | Blaze (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/desert-eagle-blaze",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "usp-s-kill-confirmed",
    weapon: "USP-S",
    name: "Kill Confirmed",
    rarity: "covert",
    image: "/assets/skins/usp-s-kill-confirmed.webp",
    skinId: "usp-s-kill-confirmed",
    value: 21572,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Kill Confirmed (Factory New)",
    marketplace: "Skins.com",
    priceSource: "https://csgoskins.gg/items/usp-s-kill-confirmed",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "glock-18-water-elemental",
    weapon: "Glock-18",
    name: "Water Elemental",
    rarity: "classified",
    image: "/assets/skins/glock-18-water-elemental.webp",
    skinId: "glock-18-water-elemental",
    value: 4000,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Glock-18 | Water Elemental (Factory New)",
    marketplace: "BUFF Market",
    priceSource: "https://csgoskins.gg/items/glock-18-water-elemental",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "usp-s-cortex",
    weapon: "USP-S",
    name: "Cortex",
    rarity: "classified",
    image: "/assets/skins/usp-s-cortex.webp",
    skinId: "usp-s-cortex",
    value: 2400,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Cortex (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/usp-s-cortex",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "usp-s-cyrex",
    weapon: "USP-S",
    name: "Cyrex",
    rarity: "restricted",
    image: "/assets/skins/usp-s-cyrex.webp",
    skinId: "usp-s-cyrex",
    value: 2757,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Cyrex (Factory New)",
    marketplace: "UUSKINS",
    priceSource: "https://csgoskins.gg/items/usp-s-cyrex",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "2 days ago",
    wearShort: "FN",
  },
  {
    id: "usp-s-ticket-to-hell",
    weapon: "USP-S",
    name: "Ticket to Hell",
    rarity: "restricted",
    image: "/assets/skins/usp-s-ticket-to-hell.webp",
    skinId: "usp-s-ticket-to-hell",
    value: 190,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Ticket to Hell (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/usp-s-ticket-to-hell",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "desert-eagle-printstream",
    weapon: "Desert Eagle",
    name: "Printstream",
    rarity: "covert",
    image: "/assets/skins/desert-eagle-printstream.webp",
    skinId: "desert-eagle-printstream",
    value: 6652,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Desert Eagle | Printstream (Factory New)",
    marketplace: "SkinBaron",
    priceSource: "https://csgoskins.gg/items/desert-eagle-printstream",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "desert-eagle-directive",
    weapon: "Desert Eagle",
    name: "Directive",
    rarity: "restricted",
    image: "/assets/skins/desert-eagle-directive.webp",
    skinId: "desert-eagle-directive",
    value: 9875,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Desert Eagle | Directive (Factory New)",
    marketplace: "Tradeit.gg",
    priceSource: "https://csgoskins.gg/items/desert-eagle-directive",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "glock-18-vogue",
    weapon: "Glock-18",
    name: "Vogue",
    rarity: "classified",
    image: "/assets/skins/glock-18-vogue.webp",
    skinId: "glock-18-vogue",
    value: 987,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Glock-18 | Vogue (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/glock-18-vogue",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "p250-nevermore",
    weapon: "P250",
    name: "Nevermore",
    rarity: "restricted",
    image: "/assets/skins/p250-nevermore.webp",
    skinId: "p250-nevermore",
    value: 171,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "P250 | Nevermore (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/p250-nevermore",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "karambit-doppler-ruby",
    weapon: "Karambit",
    name: "Doppler Ruby",
    rarity: "special",
    image: "/assets/skins/karambit-doppler-ruby.webp",
    skinId: "karambit-doppler-ruby",
    value: 736647,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: "Ruby",
    marketHashName: "★ Karambit | Doppler (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/karambit-doppler-ruby",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "3 days ago",
    wearShort: "FN",
  },
  {
    id: "butterfly-knife-fade",
    weapon: "Butterfly Knife",
    name: "Fade",
    rarity: "special",
    image: "/assets/skins/butterfly-knife-fade.webp",
    skinId: "butterfly-knife-fade",
    value: 204328,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Butterfly Knife | Fade (Factory New)",
    marketplace: "Skinport",
    priceSource: "https://csgoskins.gg/items/butterfly-knife-fade",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m9-bayonet-marble-fade",
    weapon: "M9 Bayonet",
    name: "Marble Fade",
    rarity: "special",
    image: "/assets/skins/m9-bayonet-marble-fade.webp",
    skinId: "m9-bayonet-marble-fade",
    value: 68670,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ M9 Bayonet | Marble Fade (Factory New)",
    marketplace: "SkinBaron",
    priceSource: "https://csgoskins.gg/items/m9-bayonet-marble-fade",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "talon-knife-tiger-tooth",
    weapon: "Talon Knife",
    name: "Tiger Tooth",
    rarity: "special",
    image: "/assets/skins/talon-knife-tiger-tooth.webp",
    skinId: "talon-knife-tiger-tooth",
    value: 41951,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Talon Knife | Tiger Tooth (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/talon-knife-tiger-tooth",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "huntsman-knife-slaughter",
    weapon: "Huntsman Knife",
    name: "Slaughter",
    rarity: "special",
    image: "/assets/skins/huntsman-knife-slaughter.webp",
    skinId: "huntsman-knife-slaughter",
    value: 23428,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Huntsman Knife | Slaughter (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/huntsman-knife-slaughter",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "sport-gloves-vice",
    weapon: "Sport Gloves",
    name: "Vice",
    rarity: "special",
    image: "/assets/skins/sport-gloves-vice.webp",
    skinId: "sport-gloves-vice",
    value: 550000,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Sport Gloves | Vice (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/sport-gloves-vice",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "specialist-gloves-crimson-kimono",
    weapon: "Specialist Gloves",
    name: "Crimson Kimono",
    rarity: "special",
    image: "/assets/skins/specialist-gloves-crimson-kimono.webp",
    skinId: "specialist-gloves-crimson-kimono",
    value: 865090,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Specialist Gloves | Crimson Kimono (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/specialist-gloves-crimson-kimono",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "driver-gloves-king-snake",
    weapon: "Driver Gloves",
    name: "King Snake",
    rarity: "special",
    image: "/assets/skins/driver-gloves-king-snake.webp",
    skinId: "driver-gloves-king-snake",
    value: 211576,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Driver Gloves | King Snake (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/driver-gloves-king-snake",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-ice-coaled",
    weapon: "AK-47",
    name: "Ice Coaled",
    rarity: "classified",
    image: "/assets/skins/ak-47-ice-coaled.webp",
    value: 1190,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Ice Coaled (Factory New)",
    marketplace: "UUSKINS",
    priceSource: "https://csgoskins.gg/items/ak-47-ice-coaled",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-nightwish",
    weapon: "AK-47",
    name: "Nightwish",
    rarity: "covert",
    image: "/assets/skins/ak-47-nightwish.webp",
    value: 10625,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Nightwish (Factory New)",
    marketplace: "UUSKINS",
    priceSource: "https://csgoskins.gg/items/ak-47-nightwish",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-frontside-misty",
    weapon: "AK-47",
    name: "Frontside Misty",
    rarity: "classified",
    image: "/assets/skins/ak-47-frontside-misty.webp",
    value: 10849,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Frontside Misty (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/ak-47-frontside-misty",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-aquamarine-revenge",
    weapon: "AK-47",
    name: "Aquamarine Revenge",
    rarity: "covert",
    image: "/assets/skins/ak-47-aquamarine-revenge.webp",
    value: 17753,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Aquamarine Revenge (Factory New)",
    marketplace: "Skinport",
    priceSource: "https://csgoskins.gg/items/ak-47-aquamarine-revenge",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-neon-revolution",
    weapon: "AK-47",
    name: "Neon Revolution",
    rarity: "covert",
    image: "/assets/skins/ak-47-neon-revolution.webp",
    value: 22906,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Neon Revolution (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/ak-47-neon-revolution",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-head-shot",
    weapon: "AK-47",
    name: "Head Shot",
    rarity: "covert",
    image: "/assets/skins/ak-47-head-shot.webp",
    value: 7790,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Head Shot (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/ak-47-head-shot",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-fuel-injector",
    weapon: "AK-47",
    name: "Fuel Injector",
    rarity: "covert",
    image: "/assets/skins/ak-47-fuel-injector.webp",
    value: 32483,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Fuel Injector (Factory New)",
    marketplace: "Skins.com",
    priceSource: "https://csgoskins.gg/items/ak-47-fuel-injector",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-bloodsport",
    weapon: "AK-47",
    name: "Bloodsport",
    rarity: "covert",
    image: "/assets/skins/ak-47-bloodsport.webp",
    value: 14795,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Bloodsport (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/ak-47-bloodsport",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-leet-museo",
    weapon: "AK-47",
    name: "Leet Museo",
    rarity: "covert",
    image: "/assets/skins/ak-47-leet-museo.webp",
    value: 51425,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Leet Museo (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/ak-47-leet-museo",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-uncharted",
    weapon: "AK-47",
    name: "Uncharted",
    rarity: "milspec",
    image: "/assets/skins/ak-47-uncharted.webp",
    value: 159,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Uncharted (Factory New)",
    marketplace: "Skinport",
    priceSource: "https://csgoskins.gg/items/ak-47-uncharted",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-rat-rod",
    weapon: "AK-47",
    name: "Rat Rod",
    rarity: "restricted",
    image: "/assets/skins/ak-47-rat-rod.webp",
    value: 6748,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Rat Rod (Factory New)",
    marketplace: "Tradeit.gg",
    priceSource: "https://csgoskins.gg/items/ak-47-rat-rod",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "ak-47-the-empress",
    weapon: "AK-47",
    name: "The Empress",
    rarity: "covert",
    image: "/assets/skins/ak-47-the-empress.webp",
    value: 24535,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | The Empress (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/ak-47-the-empress",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-in-living-color",
    weapon: "M4A4",
    name: "In Living Color",
    rarity: "covert",
    image: "/assets/skins/m4a4-in-living-color.webp",
    value: 8203,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | In Living Color (Factory New)",
    marketplace: "Tradeit.gg",
    priceSource: "https://csgoskins.gg/items/m4a4-in-living-color",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-desolate-space",
    weapon: "M4A4",
    name: "Desolate Space",
    rarity: "classified",
    image: "/assets/skins/m4a4-desolate-space.webp",
    value: 6735,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Desolate Space (Factory New)",
    marketplace: "Skinvault",
    priceSource: "https://csgoskins.gg/items/m4a4-desolate-space",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-neo-noir",
    weapon: "M4A4",
    name: "Neo-Noir",
    rarity: "covert",
    image: "/assets/skins/m4a4-neo-noir.webp",
    value: 8939,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Neo-Noir (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m4a4-neo-noir",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-tooth-fairy",
    weapon: "M4A4",
    name: "Tooth Fairy",
    rarity: "classified",
    image: "/assets/skins/m4a4-tooth-fairy.webp",
    value: 1138,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Tooth Fairy (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a4-tooth-fairy",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-spider-lily",
    weapon: "M4A4",
    name: "Spider Lily",
    rarity: "restricted",
    image: "/assets/skins/m4a4-spider-lily.webp",
    value: 5516,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Spider Lily (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a4-spider-lily",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "yesterday",
  },
  {
    id: "m4a4-temukau",
    weapon: "M4A4",
    name: "Temukau",
    rarity: "covert",
    image: "/assets/skins/m4a4-temukau.webp",
    value: 8727,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Temukau (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m4a4-temukau",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-buzz-kill",
    weapon: "M4A4",
    name: "Buzz Kill",
    rarity: "covert",
    image: "/assets/skins/m4a4-buzz-kill.webp",
    value: 42434,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Buzz Kill (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a4-buzz-kill",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-dragon-king",
    weapon: "M4A4",
    name: "龍王 (Dragon King)",
    rarity: "classified",
    image: "/assets/skins/m4a4-dragon-king.webp",
    value: 5090,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | 龍王 (Dragon King) (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a4-dragon-king",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "yesterday",
  },
  {
    id: "m4a4-griffin",
    weapon: "M4A4",
    name: "Griffin",
    rarity: "restricted",
    image: "/assets/skins/m4a4-griffin.webp",
    value: 6259,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Griffin (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a4-griffin",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-poseidon",
    weapon: "M4A4",
    name: "Poseidon",
    rarity: "classified",
    image: "/assets/skins/m4a4-poseidon.webp",
    value: 133791,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Poseidon (Factory New)",
    marketplace: "SkinsMonkey",
    priceSource: "https://csgoskins.gg/items/m4a4-poseidon",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-x-ray",
    weapon: "M4A4",
    name: "X-Ray",
    rarity: "covert",
    image: "/assets/skins/m4a4-x-ray.webp",
    value: 12088,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | X-Ray (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m4a4-x-ray",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a4-hellfire",
    weapon: "M4A4",
    name: "Hellfire",
    rarity: "classified",
    image: "/assets/skins/m4a4-hellfire.webp",
    value: 27980,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Hellfire (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a4-hellfire",
    priceCheckedAt: "2026-10-03T23:20:40+00:00",
    sourceAge: "2 days ago",
  },
  {
    id: "awp-neo-noir",
    weapon: "AWP",
    name: "Neo-Noir",
    rarity: "covert",
    image: "/assets/skins/awp-neo-noir.webp",
    value: 4623,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Neo-Noir (Factory New)",
    marketplace: "UUSKINS",
    priceSource: "https://csgoskins.gg/items/awp-neo-noir",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "awp-wildfire",
    weapon: "AWP",
    name: "Wildfire",
    rarity: "covert",
    image: "/assets/skins/awp-wildfire.webp",
    value: 13506,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Wildfire (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/awp-wildfire",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "awp-fever-dream",
    weapon: "AWP",
    name: "Fever Dream",
    rarity: "classified",
    image: "/assets/skins/awp-fever-dream.webp",
    value: 1610,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Fever Dream (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/awp-fever-dream",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "awp-chromatic-aberration",
    weapon: "AWP",
    name: "Chromatic Aberration",
    rarity: "covert",
    image: "/assets/skins/awp-chromatic-aberration.webp",
    value: 6400,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Chromatic Aberration (Factory New)",
    marketplace: "Tradeit.gg",
    priceSource: "https://csgoskins.gg/items/awp-chromatic-aberration",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "awp-mortis",
    weapon: "AWP",
    name: "Mortis",
    rarity: "classified",
    image: "/assets/skins/awp-mortis.webp",
    value: 1001,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Mortis (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/awp-mortis",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "awp-paw",
    weapon: "AWP",
    name: "PAW",
    rarity: "restricted",
    image: "/assets/skins/awp-paw.webp",
    value: 616,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | PAW (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/awp-paw",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "3 days ago",
  },
  {
    id: "awp-pop-awp",
    weapon: "AWP",
    name: "POP AWP",
    rarity: "restricted",
    image: "/assets/skins/awp-pop-awp.webp",
    value: 2701,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | POP AWP (Factory New)",
    marketplace: "SkinBaron",
    priceSource: "https://csgoskins.gg/items/awp-pop-awp",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "awp-pit-viper",
    weapon: "AWP",
    name: "Pit Viper",
    rarity: "restricted",
    image: "/assets/skins/awp-pit-viper.webp",
    value: 79,
    currency: "USD",
    wear: "Minimal Wear",
    wearShort: "MW",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Pit Viper (Minimal Wear)",
    marketplace: "Trackly.gg",
    priceSource: "https://csgoskins.gg/items/awp-pit-viper",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "awp-electric-hive",
    weapon: "AWP",
    name: "Electric Hive",
    rarity: "classified",
    image: "/assets/skins/awp-electric-hive.webp",
    value: 6952,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Electric Hive (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/awp-electric-hive",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "awp-sun-in-leo",
    weapon: "AWP",
    name: "Sun in Leo",
    rarity: "industrial",
    image: "/assets/skins/awp-sun-in-leo.webp",
    value: 6326,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Sun in Leo (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/awp-sun-in-leo",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a1-s-guardian",
    weapon: "M4A1-S",
    name: "Guardian",
    rarity: "classified",
    image: "/assets/skins/m4a1-s-guardian.webp",
    value: 5862,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Guardian (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m4a1-s-guardian",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a1-s-basilisk",
    weapon: "M4A1-S",
    name: "Basilisk",
    rarity: "restricted",
    image: "/assets/skins/m4a1-s-basilisk.webp",
    value: 2439,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Basilisk (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m4a1-s-basilisk",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a1-s-nightmare",
    weapon: "M4A1-S",
    name: "Nightmare",
    rarity: "classified",
    image: "/assets/skins/m4a1-s-nightmare.webp",
    value: 22737,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Nightmare (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a1-s-nightmare",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a1-s-leaded-glass",
    weapon: "M4A1-S",
    name: "Leaded Glass",
    rarity: "classified",
    image: "/assets/skins/m4a1-s-leaded-glass.webp",
    value: 3973,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Leaded Glass (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/m4a1-s-leaded-glass",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a1-s-player-two",
    weapon: "M4A1-S",
    name: "Player Two",
    rarity: "covert",
    image: "/assets/skins/m4a1-s-player-two.webp",
    value: 14322,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Player Two (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a1-s-player-two",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "2 days ago",
  },
  {
    id: "m4a1-s-golden-coil",
    weapon: "M4A1-S",
    name: "Golden Coil",
    rarity: "covert",
    image: "/assets/skins/m4a1-s-golden-coil.webp",
    value: 21878,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Golden Coil (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m4a1-s-golden-coil",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a1-s-hot-rod",
    weapon: "M4A1-S",
    name: "Hot Rod",
    rarity: "classified",
    image: "/assets/skins/m4a1-s-hot-rod.webp",
    value: 123719,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Hot Rod (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m4a1-s-hot-rod",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "m4a1-s-mecha-industries",
    weapon: "M4A1-S",
    name: "Mecha Industries",
    rarity: "covert",
    image: "/assets/skins/m4a1-s-mecha-industries.webp",
    value: 20597,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Mecha Industries (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m4a1-s-mecha-industries",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "usp-s-neo-noir",
    weapon: "USP-S",
    name: "Neo-Noir",
    rarity: "covert",
    image: "/assets/skins/usp-s-neo-noir.webp",
    value: 10000,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Neo-Noir (Factory New)",
    marketplace: "HaloSkins",
    priceSource: "https://csgoskins.gg/items/usp-s-neo-noir",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "glock-18-bullet-queen",
    weapon: "Glock-18",
    name: "Bullet Queen",
    rarity: "covert",
    image: "/assets/skins/glock-18-bullet-queen.webp",
    value: 10531,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "Glock-18 | Bullet Queen (Factory New)",
    marketplace: "Tradeit.gg",
    priceSource: "https://csgoskins.gg/items/glock-18-bullet-queen",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "desert-eagle-mecha-industries",
    weapon: "Desert Eagle",
    name: "Mecha Industries",
    rarity: "classified",
    image: "/assets/skins/desert-eagle-mecha-industries.webp",
    value: 2299,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "Desert Eagle | Mecha Industries (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/desert-eagle-mecha-industries",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "p250-asiimov",
    weapon: "P250",
    name: "Asiimov",
    rarity: "classified",
    image: "/assets/skins/p250-asiimov.webp",
    value: 2604,
    currency: "USD",
    wear: "Minimal Wear",
    wearShort: "MW",
    quality: "Normal",
    phase: null,
    marketHashName: "P250 | Asiimov (Minimal Wear)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/p250-asiimov",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "famas-roll-cage",
    weapon: "FAMAS",
    name: "Roll Cage",
    rarity: "covert",
    image: "/assets/skins/famas-roll-cage.webp",
    value: 12939,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "FAMAS | Roll Cage (Factory New)",
    marketplace: "SkinBaron",
    priceSource: "https://csgoskins.gg/items/famas-roll-cage",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "today",
  },
  {
    id: "mp9-food-chain",
    weapon: "MP9",
    name: "Food Chain",
    rarity: "classified",
    image: "/assets/skins/mp9-food-chain.webp",
    value: 1455,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "MP9 | Food Chain (Factory New)",
    marketplace: "Tradeit.gg",
    priceSource: "https://csgoskins.gg/items/mp9-food-chain",
    priceCheckedAt: "2026-10-03T23:20:47+00:00",
    sourceAge: "yesterday",
  },
  {
    id: "bowie-knife-tiger-tooth",
    weapon: "Bowie Knife",
    name: "Tiger Tooth",
    rarity: "special",
    image: "/assets/skins/bowie-knife-tiger-tooth.webp",
    value: 10525,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Bowie Knife | Tiger Tooth (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/bowie-knife-tiger-tooth",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "falchion-knife-marble-fade",
    weapon: "Falchion Knife",
    name: "Marble Fade",
    rarity: "special",
    image: "/assets/skins/falchion-knife-marble-fade.webp",
    value: 15215,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Falchion Knife | Marble Fade (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/falchion-knife-marble-fade",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "shadow-daggers-slaughter",
    weapon: "Shadow Daggers",
    name: "Slaughter",
    rarity: "special",
    image: "/assets/skins/shadow-daggers-slaughter.webp",
    value: 9131,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Shadow Daggers | Slaughter (Factory New)",
    marketplace: "Skinport",
    priceSource: "https://csgoskins.gg/items/shadow-daggers-slaughter",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "navaja-knife-fade",
    weapon: "Navaja Knife",
    name: "Fade",
    rarity: "special",
    image: "/assets/skins/navaja-knife-fade.webp",
    value: 9120,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Navaja Knife | Fade (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/navaja-knife-fade",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "3 days ago",
  },
  {
    id: "ursus-knife-tiger-tooth",
    weapon: "Ursus Knife",
    name: "Tiger Tooth",
    rarity: "special",
    image: "/assets/skins/ursus-knife-tiger-tooth.webp",
    value: 11731,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Ursus Knife | Tiger Tooth (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/ursus-knife-tiger-tooth",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "yesterday",
  },
  {
    id: "stiletto-knife-slaughter",
    weapon: "Stiletto Knife",
    name: "Slaughter",
    rarity: "special",
    image: "/assets/skins/stiletto-knife-slaughter.webp",
    value: 37062,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Stiletto Knife | Slaughter (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/stiletto-knife-slaughter",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "flip-knife-lore",
    weapon: "Flip Knife",
    name: "Lore",
    rarity: "special",
    image: "/assets/skins/flip-knife-lore.webp",
    value: 23584,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Flip Knife | Lore (Factory New)",
    marketplace: "Skins.com",
    priceSource: "https://csgoskins.gg/items/flip-knife-lore",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "4 days ago",
  },
  {
    id: "gut-knife-autotronic",
    weapon: "Gut Knife",
    name: "Autotronic",
    rarity: "special",
    image: "/assets/skins/gut-knife-autotronic.webp",
    value: 17687,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Gut Knife | Autotronic (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/gut-knife-autotronic",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "bayonet-lore",
    weapon: "Bayonet",
    name: "Lore",
    rarity: "special",
    image: "/assets/skins/bayonet-lore.webp",
    value: 39181,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Bayonet | Lore (Factory New)",
    marketplace: "CS.MONEY",
    priceSource: "https://csgoskins.gg/items/bayonet-lore",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "karambit-tiger-tooth",
    weapon: "Karambit",
    name: "Tiger Tooth",
    rarity: "special",
    image: "/assets/skins/karambit-tiger-tooth.webp",
    value: 78075,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Karambit | Tiger Tooth (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/karambit-tiger-tooth",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "butterfly-knife-slaughter",
    weapon: "Butterfly Knife",
    name: "Slaughter",
    rarity: "special",
    image: "/assets/skins/butterfly-knife-slaughter.webp",
    value: 129276,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Butterfly Knife | Slaughter (Factory New)",
    marketplace: "Aim.market",
    priceSource: "https://csgoskins.gg/items/butterfly-knife-slaughter",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "m9-bayonet-lore",
    weapon: "M9 Bayonet",
    name: "Lore",
    rarity: "special",
    image: "/assets/skins/m9-bayonet-lore.webp",
    value: 101871,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ M9 Bayonet | Lore (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/m9-bayonet-lore",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "talon-knife-crimson-web",
    weapon: "Talon Knife",
    name: "Crimson Web",
    rarity: "special",
    image: "/assets/skins/talon-knife-crimson-web.webp",
    value: 199181,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Talon Knife | Crimson Web (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/talon-knife-crimson-web",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "skeleton-knife-fade",
    weapon: "Skeleton Knife",
    name: "Fade",
    rarity: "special",
    image: "/assets/skins/skeleton-knife-fade.webp",
    value: 46458,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Skeleton Knife | Fade (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/skeleton-knife-fade",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "nomad-knife-slaughter",
    weapon: "Nomad Knife",
    name: "Slaughter",
    rarity: "special",
    image: "/assets/skins/nomad-knife-slaughter.webp",
    value: 22342,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Nomad Knife | Slaughter (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/nomad-knife-slaughter",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "yesterday",
  },
  {
    id: "classic-knife-case-hardened",
    weapon: "Classic Knife",
    name: "Case Hardened",
    rarity: "special",
    image: "/assets/skins/classic-knife-case-hardened.webp",
    value: 30300,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Classic Knife | Case Hardened (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/classic-knife-case-hardened",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "3 days ago",
  },
  {
    id: "paracord-knife-blue-steel",
    weapon: "Paracord Knife",
    name: "Blue Steel",
    rarity: "special",
    image: "/assets/skins/paracord-knife-blue-steel.webp",
    value: 12933,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Paracord Knife | Blue Steel (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/paracord-knife-blue-steel",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "survival-knife-crimson-web",
    weapon: "Survival Knife",
    name: "Crimson Web",
    rarity: "special",
    image: "/assets/skins/survival-knife-crimson-web.webp",
    value: 46266,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Survival Knife | Crimson Web (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/survival-knife-crimson-web",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "last week",
  },
  {
    id: "kukri-knife-slaughter",
    weapon: "Kukri Knife",
    name: "Slaughter",
    rarity: "special",
    image: "/assets/skins/kukri-knife-slaughter.webp",
    value: 11629,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Kukri Knife | Slaughter (Factory New)",
    marketplace: "Aim.market",
    priceSource: "https://csgoskins.gg/items/kukri-knife-slaughter",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "hand-wraps-cobalt-skulls",
    weapon: "Hand Wraps",
    name: "Cobalt Skulls",
    rarity: "special",
    image: "/assets/skins/hand-wraps-cobalt-skulls.webp",
    value: 113371,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Hand Wraps | Cobalt Skulls (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/hand-wraps-cobalt-skulls",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "yesterday",
  },
  {
    id: "moto-gloves-spearmint",
    weapon: "Moto Gloves",
    name: "Spearmint",
    rarity: "special",
    image: "/assets/skins/moto-gloves-spearmint.webp",
    value: 529464,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Moto Gloves | Spearmint (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/moto-gloves-spearmint",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "yesterday",
  },
  {
    id: "specialist-gloves-emerald-web",
    weapon: "Specialist Gloves",
    name: "Emerald Web",
    rarity: "special",
    image: "/assets/skins/specialist-gloves-emerald-web.webp",
    value: 397298,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Specialist Gloves | Emerald Web (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/specialist-gloves-emerald-web",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "yesterday",
  },
  {
    id: "sport-gloves-pandora-s-box",
    weapon: "Sport Gloves",
    name: "Pandora's Box",
    rarity: "special",
    image: "/assets/skins/sport-gloves-pandora-s-box.webp",
    value: 2176187,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Sport Gloves | Pandora's Box (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/sport-gloves-pandoras-box",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
  {
    id: "hydra-gloves-emerald",
    weapon: "Hydra Gloves",
    name: "Emerald",
    rarity: "special",
    image: "/assets/skins/hydra-gloves-emerald.webp",
    value: 15384,
    currency: "USD",
    wear: "Factory New",
    wearShort: "FN",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Hydra Gloves | Emerald (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/hydra-gloves-emerald",
    priceCheckedAt: "2026-10-03T23:20:11Z",
    sourceAge: "today",
  },
];
export const skinById = new Map(skins.map((skin) => [skin.id, skin]));
const caseDefinitions = [
  {
    id: "ember",
    name: "Разогрев",
    subtitle: "Первый шаг к большому дропу",
    color: "#ff873b",
    image: "/assets/cases/case-1.webp",
    drops: [
      {
        skinId: "ak-47-elite-build",
        weight: 2409,
      },
      {
        skinId: "ak-47-slate",
        weight: 1820,
      },
      {
        skinId: "desert-eagle-directive",
        weight: 1383,
      },
      {
        skinId: "ak-47-redline",
        weight: 1051,
      },
      {
        skinId: "huntsman-knife-slaughter",
        weight: 799,
      },
      {
        skinId: "ak-47-asiimov",
        weight: 607,
      },
      {
        skinId: "ak-47-uncharted",
        weight: 462,
      },
      {
        skinId: "ak-47-rat-rod",
        weight: 351,
      },
      {
        skinId: "m4a4-griffin",
        weight: 267,
      },
      {
        skinId: "p250-asiimov",
        weight: 203,
      },
      {
        skinId: "m4a4-tooth-fairy",
        weight: 154,
      },
      {
        skinId: "m4a4-spider-lily",
        weight: 117,
      },
      {
        skinId: "m4a1-s-basilisk",
        weight: 89,
      },
      {
        skinId: "m4a1-s-guardian",
        weight: 68,
      },
      {
        skinId: "awp-paw",
        weight: 52,
      },
      {
        skinId: "awp-mortis",
        weight: 40,
      },
      {
        skinId: "awp-pit-viper",
        weight: 30,
      },
      {
        skinId: "awp-fever-dream",
        weight: 23,
      },
      {
        skinId: "awp-sun-in-leo",
        weight: 18,
      },
      {
        skinId: "m4a1-s-mecha-industries",
        weight: 14,
      },
      {
        skinId: "desert-eagle-mecha-industries",
        weight: 10,
      },
      {
        skinId: "mp9-food-chain",
        weight: 8,
      },
      {
        skinId: "famas-roll-cage",
        weight: 6,
      },
      {
        skinId: "m4a1-s-leaded-glass",
        weight: 5,
      },
      {
        skinId: "ak-47-ice-coaled",
        weight: 4,
      },
      {
        skinId: "awp-electric-hive",
        weight: 3,
      },
      {
        skinId: "ak-47-frontside-misty",
        weight: 2,
      },
      {
        skinId: "m4a4-desolate-space",
        weight: 2,
      },
      {
        skinId: "m4a4-buzz-kill",
        weight: 2,
      },
      {
        skinId: "ak-47-aquamarine-revenge",
        weight: 1,
      },
    ],
  },
  {
    id: "toxic",
    name: "Токсик",
    subtitle: "Опасно яркий",
    color: "#b4ec42",
    image: "/assets/cases/case-2.webp",
    drops: [
      {
        skinId: "m4a4-magnesium",
        weight: 2409,
      },
      {
        skinId: "ak-47-phantom-disruptor",
        weight: 1820,
      },
      {
        skinId: "awp-atheris",
        weight: 1383,
      },
      {
        skinId: "usp-s-cyrex",
        weight: 1051,
      },
      {
        skinId: "awp-containment-breach",
        weight: 799,
      },
      {
        skinId: "m9-bayonet-marble-fade",
        weight: 607,
      },
      {
        skinId: "ak-47-aquamarine-revenge",
        weight: 462,
      },
      {
        skinId: "ak-47-ice-coaled",
        weight: 351,
      },
      {
        skinId: "awp-pit-viper",
        weight: 267,
      },
      {
        skinId: "m4a1-s-leaded-glass",
        weight: 203,
      },
      {
        skinId: "m4a1-s-guardian",
        weight: 154,
      },
      {
        skinId: "mp9-food-chain",
        weight: 117,
      },
      {
        skinId: "awp-paw",
        weight: 89,
      },
      {
        skinId: "m4a4-griffin",
        weight: 68,
      },
      {
        skinId: "ak-47-uncharted",
        weight: 52,
      },
      {
        skinId: "ak-47-rat-rod",
        weight: 40,
      },
      {
        skinId: "ak-47-fuel-injector",
        weight: 30,
      },
      {
        skinId: "m4a4-buzz-kill",
        weight: 23,
      },
      {
        skinId: "m4a1-s-golden-coil",
        weight: 18,
      },
      {
        skinId: "m4a4-poseidon",
        weight: 14,
      },
      {
        skinId: "m4a1-s-basilisk",
        weight: 10,
      },
      {
        skinId: "awp-pop-awp",
        weight: 8,
      },
      {
        skinId: "awp-sun-in-leo",
        weight: 6,
      },
      {
        skinId: "m4a1-s-nightmare",
        weight: 5,
      },
      {
        skinId: "m4a4-spider-lily",
        weight: 4,
      },
      {
        skinId: "m4a4-tooth-fairy",
        weight: 3,
      },
      {
        skinId: "awp-electric-hive",
        weight: 2,
      },
      {
        skinId: "awp-mortis",
        weight: 2,
      },
      {
        skinId: "m4a4-desolate-space",
        weight: 2,
      },
      {
        skinId: "m4a4-in-living-color",
        weight: 1,
      },
    ],
  },
  {
    id: "frost",
    name: "Ледниковый",
    subtitle: "Холодный расчёт",
    color: "#68cdff",
    image: "/assets/cases/case-3.webp",
    drops: [
      {
        skinId: "ssg-08-abyss",
        weight: 2409,
      },
      {
        skinId: "m4a1-s-decimator",
        weight: 1820,
      },
      {
        skinId: "glock-18-water-elemental",
        weight: 1383,
      },
      {
        skinId: "desert-eagle-printstream",
        weight: 1051,
      },
      {
        skinId: "awp-asiimov",
        weight: 799,
      },
      {
        skinId: "driver-gloves-king-snake",
        weight: 607,
      },
      {
        skinId: "ak-47-frontside-misty",
        weight: 462,
      },
      {
        skinId: "ak-47-ice-coaled",
        weight: 351,
      },
      {
        skinId: "m4a4-poseidon",
        weight: 267,
      },
      {
        skinId: "m4a1-s-guardian",
        weight: 203,
      },
      {
        skinId: "m4a1-s-basilisk",
        weight: 154,
      },
      {
        skinId: "m4a1-s-mecha-industries",
        weight: 117,
      },
      {
        skinId: "desert-eagle-mecha-industries",
        weight: 89,
      },
      {
        skinId: "m4a4-neo-noir",
        weight: 68,
      },
      {
        skinId: "awp-neo-noir",
        weight: 52,
      },
      {
        skinId: "usp-s-neo-noir",
        weight: 40,
      },
      {
        skinId: "awp-sun-in-leo",
        weight: 30,
      },
      {
        skinId: "awp-electric-hive",
        weight: 23,
      },
      {
        skinId: "ak-47-aquamarine-revenge",
        weight: 18,
      },
      {
        skinId: "m4a1-s-leaded-glass",
        weight: 14,
      },
      {
        skinId: "m4a4-desolate-space",
        weight: 10,
      },
      {
        skinId: "m4a4-temukau",
        weight: 8,
      },
      {
        skinId: "m4a4-griffin",
        weight: 6,
      },
      {
        skinId: "m4a4-spider-lily",
        weight: 5,
      },
      {
        skinId: "awp-pop-awp",
        weight: 4,
      },
      {
        skinId: "awp-paw",
        weight: 3,
      },
      {
        skinId: "awp-pit-viper",
        weight: 2,
      },
      {
        skinId: "mp9-food-chain",
        weight: 2,
      },
      {
        skinId: "m4a1-s-player-two",
        weight: 2,
      },
      {
        skinId: "awp-fever-dream",
        weight: 1,
      },
    ],
  },
  {
    id: "neon",
    name: "Неон",
    subtitle: "Ночная смена",
    color: "#b381ff",
    image: "/assets/cases/case-4.webp",
    drops: [
      {
        skinId: "usp-s-ticket-to-hell",
        weight: 2409,
      },
      {
        skinId: "glock-18-vogue",
        weight: 1820,
      },
      {
        skinId: "m4a1-s-decimator",
        weight: 1383,
      },
      {
        skinId: "ak-47-neon-rider",
        weight: 1051,
      },
      {
        skinId: "m4a1-s-hyper-beast",
        weight: 799,
      },
      {
        skinId: "sport-gloves-vice",
        weight: 607,
      },
      {
        skinId: "ak-47-nightwish",
        weight: 462,
      },
      {
        skinId: "ak-47-neon-revolution",
        weight: 351,
      },
      {
        skinId: "ak-47-head-shot",
        weight: 267,
      },
      {
        skinId: "ak-47-leet-museo",
        weight: 203,
      },
      {
        skinId: "m4a4-in-living-color",
        weight: 154,
      },
      {
        skinId: "awp-chromatic-aberration",
        weight: 117,
      },
      {
        skinId: "awp-fever-dream",
        weight: 89,
      },
      {
        skinId: "mp9-food-chain",
        weight: 68,
      },
      {
        skinId: "glock-18-bullet-queen",
        weight: 52,
      },
      {
        skinId: "m4a1-s-player-two",
        weight: 40,
      },
      {
        skinId: "m4a4-temukau",
        weight: 30,
      },
      {
        skinId: "m4a4-neo-noir",
        weight: 23,
      },
      {
        skinId: "awp-neo-noir",
        weight: 18,
      },
      {
        skinId: "usp-s-neo-noir",
        weight: 14,
      },
      {
        skinId: "awp-pop-awp",
        weight: 10,
      },
      {
        skinId: "awp-wildfire",
        weight: 8,
      },
      {
        skinId: "m4a4-spider-lily",
        weight: 6,
      },
      {
        skinId: "m4a4-tooth-fairy",
        weight: 5,
      },
      {
        skinId: "m4a4-desolate-space",
        weight: 4,
      },
      {
        skinId: "ak-47-aquamarine-revenge",
        weight: 3,
      },
      {
        skinId: "ak-47-bloodsport",
        weight: 2,
      },
      {
        skinId: "ak-47-frontside-misty",
        weight: 2,
      },
      {
        skinId: "ak-47-ice-coaled",
        weight: 2,
      },
      {
        skinId: "ak-47-rat-rod",
        weight: 1,
      },
    ],
  },
  {
    id: "samurai",
    name: "Самурай",
    subtitle: "Один точный удар",
    color: "#ff5272",
    image: "/assets/cases/case-5.webp",
    drops: [
      {
        skinId: "m4a4-evil-daimyo",
        weight: 2409,
      },
      {
        skinId: "usp-s-cortex",
        weight: 1820,
      },
      {
        skinId: "ak-47-redline",
        weight: 1383,
      },
      {
        skinId: "usp-s-kill-confirmed",
        weight: 1051,
      },
      {
        skinId: "ak-47-fire-serpent",
        weight: 799,
      },
      {
        skinId: "karambit-doppler-ruby",
        weight: 607,
      },
      {
        skinId: "m4a4-temukau",
        weight: 462,
      },
      {
        skinId: "m4a4-dragon-king",
        weight: 351,
      },
      {
        skinId: "ak-47-the-empress",
        weight: 267,
      },
      {
        skinId: "ak-47-bloodsport",
        weight: 203,
      },
      {
        skinId: "ak-47-leet-museo",
        weight: 154,
      },
      {
        skinId: "ak-47-head-shot",
        weight: 117,
      },
      {
        skinId: "m4a1-s-player-two",
        weight: 89,
      },
      {
        skinId: "glock-18-bullet-queen",
        weight: 68,
      },
      {
        skinId: "ak-47-neon-revolution",
        weight: 52,
      },
      {
        skinId: "ak-47-nightwish",
        weight: 40,
      },
      {
        skinId: "m4a4-neo-noir",
        weight: 30,
      },
      {
        skinId: "awp-neo-noir",
        weight: 23,
      },
      {
        skinId: "usp-s-neo-noir",
        weight: 18,
      },
      {
        skinId: "m4a4-hellfire",
        weight: 14,
      },
      {
        skinId: "m4a4-x-ray",
        weight: 10,
      },
      {
        skinId: "awp-wildfire",
        weight: 8,
      },
      {
        skinId: "m4a1-s-golden-coil",
        weight: 6,
      },
      {
        skinId: "ak-47-fuel-injector",
        weight: 5,
      },
      {
        skinId: "awp-mortis",
        weight: 4,
      },
      {
        skinId: "m4a4-tooth-fairy",
        weight: 3,
      },
      {
        skinId: "m4a4-spider-lily",
        weight: 2,
      },
      {
        skinId: "m4a4-griffin",
        weight: 2,
      },
      {
        skinId: "m4a1-s-basilisk",
        weight: 2,
      },
      {
        skinId: "m4a1-s-guardian",
        weight: 1,
      },
    ],
  },
  {
    id: "royal",
    name: "Королевский",
    subtitle: "Для тех, кто любит золото",
    color: "#edca62",
    image: "/assets/cases/case-6.webp",
    drops: [
      {
        skinId: "ak-47-slate",
        weight: 2409,
      },
      {
        skinId: "ak-47-phantom-disruptor",
        weight: 1820,
      },
      {
        skinId: "awp-asiimov",
        weight: 1383,
      },
      {
        skinId: "talon-knife-tiger-tooth",
        weight: 1051,
      },
      {
        skinId: "desert-eagle-blaze",
        weight: 799,
      },
      {
        skinId: "awp-dragon-lore",
        weight: 607,
      },
      {
        skinId: "ak-47-fuel-injector",
        weight: 462,
      },
      {
        skinId: "m4a4-buzz-kill",
        weight: 351,
      },
      {
        skinId: "m4a1-s-golden-coil",
        weight: 267,
      },
      {
        skinId: "ak-47-the-empress",
        weight: 203,
      },
      {
        skinId: "awp-sun-in-leo",
        weight: 154,
      },
      {
        skinId: "m4a1-s-hot-rod",
        weight: 117,
      },
      {
        skinId: "ak-47-bloodsport",
        weight: 89,
      },
      {
        skinId: "m4a4-poseidon",
        weight: 68,
      },
      {
        skinId: "m4a4-dragon-king",
        weight: 52,
      },
      {
        skinId: "awp-wildfire",
        weight: 40,
      },
      {
        skinId: "m4a4-x-ray",
        weight: 30,
      },
      {
        skinId: "m4a4-hellfire",
        weight: 23,
      },
      {
        skinId: "awp-electric-hive",
        weight: 18,
      },
      {
        skinId: "ak-47-leet-museo",
        weight: 14,
      },
      {
        skinId: "ak-47-head-shot",
        weight: 10,
      },
      {
        skinId: "m4a1-s-player-two",
        weight: 8,
      },
      {
        skinId: "glock-18-bullet-queen",
        weight: 6,
      },
      {
        skinId: "m4a4-in-living-color",
        weight: 5,
      },
      {
        skinId: "m4a4-temukau",
        weight: 4,
      },
      {
        skinId: "ak-47-aquamarine-revenge",
        weight: 3,
      },
      {
        skinId: "ak-47-frontside-misty",
        weight: 2,
      },
      {
        skinId: "m4a1-s-mecha-industries",
        weight: 2,
      },
      {
        skinId: "desert-eagle-mecha-industries",
        weight: 2,
      },
      {
        skinId: "m4a4-neo-noir",
        weight: 1,
      },
    ],
  },
  {
    id: "ghost",
    name: "Призрак",
    subtitle: "Появляется из ниоткуда",
    color: "#c1d2e3",
    image: "/assets/cases/case-7.webp",
    drops: [
      {
        skinId: "usp-s-cyrex",
        weight: 2409,
      },
      {
        skinId: "m4a1-s-decimator",
        weight: 1820,
      },
      {
        skinId: "desert-eagle-printstream",
        weight: 1383,
      },
      {
        skinId: "awp-hyper-beast",
        weight: 1051,
      },
      {
        skinId: "butterfly-knife-fade",
        weight: 799,
      },
      {
        skinId: "driver-gloves-king-snake",
        weight: 607,
      },
      {
        skinId: "m4a1-s-mecha-industries",
        weight: 462,
      },
      {
        skinId: "desert-eagle-mecha-industries",
        weight: 351,
      },
      {
        skinId: "m4a4-neo-noir",
        weight: 267,
      },
      {
        skinId: "awp-neo-noir",
        weight: 203,
      },
      {
        skinId: "usp-s-neo-noir",
        weight: 154,
      },
      {
        skinId: "m4a1-s-guardian",
        weight: 117,
      },
      {
        skinId: "m4a1-s-basilisk",
        weight: 89,
      },
      {
        skinId: "m4a1-s-leaded-glass",
        weight: 68,
      },
      {
        skinId: "m4a1-s-nightmare",
        weight: 52,
      },
      {
        skinId: "m4a4-spider-lily",
        weight: 40,
      },
      {
        skinId: "awp-electric-hive",
        weight: 30,
      },
      {
        skinId: "ak-47-ice-coaled",
        weight: 23,
      },
      {
        skinId: "m4a4-desolate-space",
        weight: 18,
      },
      {
        skinId: "m4a4-griffin",
        weight: 14,
      },
      {
        skinId: "m4a4-tooth-fairy",
        weight: 10,
      },
      {
        skinId: "ak-47-rat-rod",
        weight: 8,
      },
      {
        skinId: "ak-47-uncharted",
        weight: 6,
      },
      {
        skinId: "awp-pit-viper",
        weight: 5,
      },
      {
        skinId: "awp-paw",
        weight: 4,
      },
      {
        skinId: "awp-mortis",
        weight: 3,
      },
      {
        skinId: "awp-pop-awp",
        weight: 2,
      },
      {
        skinId: "awp-fever-dream",
        weight: 2,
      },
      {
        skinId: "ak-47-frontside-misty",
        weight: 2,
      },
      {
        skinId: "ak-47-aquamarine-revenge",
        weight: 1,
      },
    ],
  },
  {
    id: "inferno",
    name: "Инферно",
    subtitle: "Температура на максимуме",
    color: "#ff5f3a",
    image: "/assets/cases/case-8.webp",
    drops: [
      {
        skinId: "p250-nevermore",
        weight: 2409,
      },
      {
        skinId: "usp-s-kill-confirmed",
        weight: 1820,
      },
      {
        skinId: "ak-47-asiimov",
        weight: 1383,
      },
      {
        skinId: "ak-47-fire-serpent",
        weight: 1051,
      },
      {
        skinId: "m4a4-howl",
        weight: 799,
      },
      {
        skinId: "specialist-gloves-crimson-kimono",
        weight: 607,
      },
      {
        skinId: "awp-wildfire",
        weight: 462,
      },
      {
        skinId: "m4a1-s-hot-rod",
        weight: 351,
      },
      {
        skinId: "ak-47-head-shot",
        weight: 267,
      },
      {
        skinId: "ak-47-neon-revolution",
        weight: 203,
      },
      {
        skinId: "glock-18-bullet-queen",
        weight: 154,
      },
      {
        skinId: "famas-roll-cage",
        weight: 117,
      },
      {
        skinId: "ak-47-nightwish",
        weight: 89,
      },
      {
        skinId: "m4a4-x-ray",
        weight: 68,
      },
      {
        skinId: "m4a4-hellfire",
        weight: 52,
      },
      {
        skinId: "ak-47-the-empress",
        weight: 40,
      },
      {
        skinId: "m4a1-s-golden-coil",
        weight: 30,
      },
      {
        skinId: "ak-47-fuel-injector",
        weight: 23,
      },
      {
        skinId: "ak-47-bloodsport",
        weight: 18,
      },
      {
        skinId: "m4a4-in-living-color",
        weight: 14,
      },
      {
        skinId: "m4a4-dragon-king",
        weight: 10,
      },
      {
        skinId: "ak-47-leet-museo",
        weight: 8,
      },
      {
        skinId: "awp-chromatic-aberration",
        weight: 6,
      },
      {
        skinId: "awp-fever-dream",
        weight: 5,
      },
      {
        skinId: "m4a1-s-player-two",
        weight: 4,
      },
      {
        skinId: "m4a4-temukau",
        weight: 3,
      },
      {
        skinId: "awp-mortis",
        weight: 2,
      },
      {
        skinId: "m4a4-buzz-kill",
        weight: 2,
      },
      {
        skinId: "ak-47-rat-rod",
        weight: 2,
      },
      {
        skinId: "mp9-food-chain",
        weight: 1,
      },
    ],
  },
  {
    id: "cosmos",
    name: "Космос",
    subtitle: "За пределами обычного",
    color: "#698aff",
    image: "/assets/cases/case-9.webp",
    drops: [
      {
        skinId: "ak-47-neon-rider",
        weight: 2409,
      },
      {
        skinId: "awp-containment-breach",
        weight: 1820,
      },
      {
        skinId: "m9-bayonet-marble-fade",
        weight: 1383,
      },
      {
        skinId: "sport-gloves-vice",
        weight: 1051,
      },
      {
        skinId: "karambit-doppler-ruby",
        weight: 799,
      },
      {
        skinId: "awp-dragon-lore",
        weight: 607,
      },
      {
        skinId: "ak-47-nightwish",
        weight: 462,
      },
      {
        skinId: "awp-chromatic-aberration",
        weight: 351,
      },
      {
        skinId: "m4a4-neo-noir",
        weight: 267,
      },
      {
        skinId: "awp-neo-noir",
        weight: 203,
      },
      {
        skinId: "usp-s-neo-noir",
        weight: 154,
      },
      {
        skinId: "m4a4-desolate-space",
        weight: 117,
      },
      {
        skinId: "m4a4-in-living-color",
        weight: 89,
      },
      {
        skinId: "ak-47-leet-museo",
        weight: 68,
      },
      {
        skinId: "ak-47-head-shot",
        weight: 52,
      },
      {
        skinId: "ak-47-neon-revolution",
        weight: 40,
      },
      {
        skinId: "awp-fever-dream",
        weight: 30,
      },
      {
        skinId: "m4a1-s-player-two",
        weight: 23,
      },
      {
        skinId: "m4a4-temukau",
        weight: 18,
      },
      {
        skinId: "m4a1-s-nightmare",
        weight: 14,
      },
      {
        skinId: "ak-47-bloodsport",
        weight: 10,
      },
      {
        skinId: "ak-47-the-empress",
        weight: 8,
      },
      {
        skinId: "m4a4-poseidon",
        weight: 6,
      },
      {
        skinId: "awp-wildfire",
        weight: 5,
      },
      {
        skinId: "ak-47-aquamarine-revenge",
        weight: 4,
      },
      {
        skinId: "ak-47-frontside-misty",
        weight: 3,
      },
      {
        skinId: "awp-electric-hive",
        weight: 2,
      },
      {
        skinId: "ak-47-ice-coaled",
        weight: 2,
      },
      {
        skinId: "m4a1-s-hot-rod",
        weight: 2,
      },
      {
        skinId: "m4a4-x-ray",
        weight: 1,
      },
    ],
  },
  {
    id: "diamond",
    name: "Чёрный бриллиант",
    subtitle: "Только особые предметы",
    color: "#e2c477",
    image: "/assets/cases/case-10.webp",
    drops: [
      {
        skinId: "huntsman-knife-slaughter",
        weight: 2409,
      },
      {
        skinId: "talon-knife-tiger-tooth",
        weight: 1820,
      },
      {
        skinId: "m9-bayonet-marble-fade",
        weight: 1383,
      },
      {
        skinId: "butterfly-knife-fade",
        weight: 1051,
      },
      {
        skinId: "driver-gloves-king-snake",
        weight: 799,
      },
      {
        skinId: "karambit-doppler-ruby",
        weight: 607,
      },
      {
        skinId: "bowie-knife-tiger-tooth",
        weight: 462,
      },
      {
        skinId: "falchion-knife-marble-fade",
        weight: 351,
      },
      {
        skinId: "shadow-daggers-slaughter",
        weight: 267,
      },
      {
        skinId: "navaja-knife-fade",
        weight: 203,
      },
      {
        skinId: "ursus-knife-tiger-tooth",
        weight: 154,
      },
      {
        skinId: "stiletto-knife-slaughter",
        weight: 117,
      },
      {
        skinId: "flip-knife-lore",
        weight: 89,
      },
      {
        skinId: "gut-knife-autotronic",
        weight: 68,
      },
      {
        skinId: "bayonet-lore",
        weight: 52,
      },
      {
        skinId: "karambit-tiger-tooth",
        weight: 40,
      },
      {
        skinId: "butterfly-knife-slaughter",
        weight: 30,
      },
      {
        skinId: "m9-bayonet-lore",
        weight: 23,
      },
      {
        skinId: "talon-knife-crimson-web",
        weight: 18,
      },
      {
        skinId: "skeleton-knife-fade",
        weight: 14,
      },
      {
        skinId: "nomad-knife-slaughter",
        weight: 10,
      },
      {
        skinId: "classic-knife-case-hardened",
        weight: 8,
      },
      {
        skinId: "paracord-knife-blue-steel",
        weight: 6,
      },
      {
        skinId: "survival-knife-crimson-web",
        weight: 5,
      },
      {
        skinId: "kukri-knife-slaughter",
        weight: 4,
      },
      {
        skinId: "hand-wraps-cobalt-skulls",
        weight: 3,
      },
      {
        skinId: "moto-gloves-spearmint",
        weight: 2,
      },
      {
        skinId: "specialist-gloves-emerald-web",
        weight: 2,
      },
      {
        skinId: "sport-gloves-pandora-s-box",
        weight: 2,
      },
      {
        skinId: "hydra-gloves-emerald",
        weight: 1,
      },
    ],
  },
];
export const cases = caseDefinitions.map((item) => ({
  ...item,
  ...priceCase(
    item.drops,
    skinById,
    item.drops.map((drop) => drop.weight),
  ),
}));
export const caseById = new Map(cases.map((item) => [item.id, item]));
export const rarities = {
  industrial: {
    name: "Промышленное",
    color: "#81b4ce",
  },
  milspec: {
    name: "Армейское",
    color: "#659cff",
  },
  restricted: {
    name: "Запрещённое",
    color: "#ae7dff",
  },
  classified: {
    name: "Засекреченное",
    color: "#e374e4",
  },
  covert: {
    name: "Тайное",
    color: "#ff646d",
  },
  special: {
    name: "Особое",
    color: "#f0c765",
  },
  contraband: {
    name: "Контрабанда",
    color: "#eea35b",
  },
};
