import { priceCase } from "./pricing.js";
export const skins = [
  {
    id: "ak-47-redline",
    weapon: "AK-47",
    name: "Redline",
    rarity: "classified",
    image: "/assets/skins/ak-47-redline.webp",
    skinId: "ak-47-redline",
    value: 12349,
    currency: "USD",
    wear: "Minimal Wear",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Redline (Minimal Wear)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/ak-47-redline",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "MW",
  },
  {
    id: "ak-47-asiimov",
    weapon: "AK-47",
    name: "Asiimov",
    rarity: "covert",
    image: "/assets/skins/ak-47-asiimov.webp",
    skinId: "ak-47-asiimov",
    value: 28947,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Asiimov (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/ak-47-asiimov",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-neon-rider",
    weapon: "AK-47",
    name: "Neon Rider",
    rarity: "covert",
    image: "/assets/skins/ak-47-neon-rider.webp",
    skinId: "ak-47-neon-rider",
    value: 19329,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Neon Rider (Factory New)",
    marketplace: "Skins.com",
    priceSource: "https://csgoskins.gg/items/ak-47-neon-rider",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-fire-serpent",
    weapon: "AK-47",
    name: "Fire Serpent",
    rarity: "covert",
    image: "/assets/skins/ak-47-fire-serpent.webp",
    skinId: "ak-47-fire-serpent",
    value: 210464,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Fire Serpent (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/ak-47-fire-serpent",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-slate",
    weapon: "AK-47",
    name: "Slate",
    rarity: "restricted",
    image: "/assets/skins/ak-47-slate.webp",
    skinId: "ak-47-slate",
    value: 1310,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Slate (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/ak-47-slate",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-elite-build",
    weapon: "AK-47",
    name: "Elite Build",
    rarity: "milspec",
    image: "/assets/skins/ak-47-elite-build.webp",
    skinId: "ak-47-elite-build",
    value: 716,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Elite Build (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/ak-47-elite-build",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ak-47-phantom-disruptor",
    weapon: "AK-47",
    name: "Phantom Disruptor",
    rarity: "classified",
    image: "/assets/skins/ak-47-phantom-disruptor.webp",
    skinId: "ak-47-phantom-disruptor",
    value: 1826,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AK-47 | Phantom Disruptor (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/ak-47-phantom-disruptor",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a4-howl",
    weapon: "M4A4",
    name: "Howl",
    rarity: "contraband",
    image: "/assets/skins/m4a4-howl.webp",
    skinId: "m4a4-howl",
    value: 659075,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Howl (Factory New)",
    marketplace: "Skinport",
    priceSource: "https://csgoskins.gg/items/m4a4-howl",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a4-evil-daimyo",
    weapon: "M4A4",
    name: "Evil Daimyo",
    rarity: "restricted",
    image: "/assets/skins/m4a4-evil-daimyo.webp",
    skinId: "m4a4-evil-daimyo",
    value: 751,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Evil Daimyo (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/m4a4-evil-daimyo",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a4-magnesium",
    weapon: "M4A4",
    name: "Magnesium",
    rarity: "milspec",
    image: "/assets/skins/m4a4-magnesium.webp",
    skinId: "m4a4-magnesium",
    value: 512,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A4 | Magnesium (Factory New)",
    marketplace: "UUSKINS",
    priceSource: "https://csgoskins.gg/items/m4a4-magnesium",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a1-s-hyper-beast",
    weapon: "M4A1-S",
    name: "Hyper Beast",
    rarity: "covert",
    image: "/assets/skins/m4a1-s-hyper-beast.webp",
    skinId: "m4a1-s-hyper-beast",
    value: 26118,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Hyper Beast (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/m4a1-s-hyper-beast",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m4a1-s-decimator",
    weapon: "M4A1-S",
    name: "Decimator",
    rarity: "classified",
    image: "/assets/skins/m4a1-s-decimator.webp",
    skinId: "m4a1-s-decimator",
    value: 3898,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "M4A1-S | Decimator (Factory New)",
    marketplace: "DMarket",
    priceSource: "https://csgoskins.gg/items/m4a1-s-decimator",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "awp-asiimov",
    weapon: "AWP",
    name: "Asiimov",
    rarity: "covert",
    image: "/assets/skins/awp-asiimov.webp",
    skinId: "awp-asiimov",
    value: 9873,
    currency: "USD",
    wear: "Field-Tested",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Asiimov (Field-Tested)",
    marketplace: "Aim.market",
    priceSource: "https://csgoskins.gg/items/awp-asiimov",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FT",
  },
  {
    id: "awp-hyper-beast",
    weapon: "AWP",
    name: "Hyper Beast",
    rarity: "covert",
    image: "/assets/skins/awp-hyper-beast.webp",
    skinId: "awp-hyper-beast",
    value: 14404,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Hyper Beast (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/awp-hyper-beast",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "awp-dragon-lore",
    weapon: "AWP",
    name: "Dragon Lore",
    rarity: "covert",
    image: "/assets/skins/awp-dragon-lore.webp",
    skinId: "awp-dragon-lore",
    value: 1085304,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Dragon Lore (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/awp-dragon-lore",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "awp-containment-breach",
    weapon: "AWP",
    name: "Containment Breach",
    rarity: "covert",
    image: "/assets/skins/awp-containment-breach.webp",
    skinId: "awp-containment-breach",
    value: 37122,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Containment Breach (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/awp-containment-breach",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "awp-atheris",
    weapon: "AWP",
    name: "Atheris",
    rarity: "restricted",
    image: "/assets/skins/awp-atheris.webp",
    skinId: "awp-atheris",
    value: 2512,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "AWP | Atheris (Factory New)",
    marketplace: "SkinsMonkey",
    priceSource: "https://csgoskins.gg/items/awp-atheris",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "ssg-08-abyss",
    weapon: "SSG 08",
    name: "Abyss",
    rarity: "milspec",
    image: "/assets/skins/ssg-08-abyss.webp",
    skinId: "ssg-08-abyss",
    value: 383,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "SSG 08 | Abyss (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/ssg-08-abyss",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "desert-eagle-blaze",
    weapon: "Desert Eagle",
    name: "Blaze",
    rarity: "restricted",
    image: "/assets/skins/desert-eagle-blaze.webp",
    skinId: "desert-eagle-blaze",
    value: 57500,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Desert Eagle | Blaze (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/desert-eagle-blaze",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "usp-s-kill-confirmed",
    weapon: "USP-S",
    name: "Kill Confirmed",
    rarity: "covert",
    image: "/assets/skins/usp-s-kill-confirmed.webp",
    skinId: "usp-s-kill-confirmed",
    value: 21572,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Kill Confirmed (Factory New)",
    marketplace: "Skins.com",
    priceSource: "https://csgoskins.gg/items/usp-s-kill-confirmed",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "glock-18-water-elemental",
    weapon: "Glock-18",
    name: "Water Elemental",
    rarity: "classified",
    image: "/assets/skins/glock-18-water-elemental.webp",
    skinId: "glock-18-water-elemental",
    value: 4000,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Glock-18 | Water Elemental (Factory New)",
    marketplace: "BUFF Market",
    priceSource: "https://csgoskins.gg/items/glock-18-water-elemental",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "usp-s-cortex",
    weapon: "USP-S",
    name: "Cortex",
    rarity: "classified",
    image: "/assets/skins/usp-s-cortex.webp",
    skinId: "usp-s-cortex",
    value: 2400,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Cortex (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/usp-s-cortex",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "usp-s-cyrex",
    weapon: "USP-S",
    name: "Cyrex",
    rarity: "restricted",
    image: "/assets/skins/usp-s-cyrex.webp",
    skinId: "usp-s-cyrex",
    value: 2757,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Cyrex (Factory New)",
    marketplace: "UUSKINS",
    priceSource: "https://csgoskins.gg/items/usp-s-cyrex",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "2 days ago",
    wearShort: "FN",
  },
  {
    id: "usp-s-ticket-to-hell",
    weapon: "USP-S",
    name: "Ticket to Hell",
    rarity: "restricted",
    image: "/assets/skins/usp-s-ticket-to-hell.webp",
    skinId: "usp-s-ticket-to-hell",
    value: 190,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "USP-S | Ticket to Hell (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/usp-s-ticket-to-hell",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "desert-eagle-printstream",
    weapon: "Desert Eagle",
    name: "Printstream",
    rarity: "covert",
    image: "/assets/skins/desert-eagle-printstream.webp",
    skinId: "desert-eagle-printstream",
    value: 6652,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Desert Eagle | Printstream (Factory New)",
    marketplace: "SkinBaron",
    priceSource: "https://csgoskins.gg/items/desert-eagle-printstream",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "desert-eagle-directive",
    weapon: "Desert Eagle",
    name: "Directive",
    rarity: "restricted",
    image: "/assets/skins/desert-eagle-directive.webp",
    skinId: "desert-eagle-directive",
    value: 9875,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Desert Eagle | Directive (Factory New)",
    marketplace: "Tradeit.gg",
    priceSource: "https://csgoskins.gg/items/desert-eagle-directive",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "glock-18-vogue",
    weapon: "Glock-18",
    name: "Vogue",
    rarity: "classified",
    image: "/assets/skins/glock-18-vogue.webp",
    skinId: "glock-18-vogue",
    value: 987,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "Glock-18 | Vogue (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/glock-18-vogue",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "p250-nevermore",
    weapon: "P250",
    name: "Nevermore",
    rarity: "restricted",
    image: "/assets/skins/p250-nevermore.webp",
    skinId: "p250-nevermore",
    value: 171,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "P250 | Nevermore (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/p250-nevermore",
    priceCheckedAt: "2026-10-03T22:54:07+00:00",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "karambit-doppler-ruby",
    weapon: "Karambit",
    name: "Doppler Ruby",
    rarity: "special",
    image: "/assets/skins/karambit-doppler-ruby.webp",
    skinId: "karambit-doppler-ruby",
    value: 736647,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: "Ruby",
    marketHashName: "★ Karambit | Doppler (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/karambit-doppler-ruby",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "3 days ago",
    wearShort: "FN",
  },
  {
    id: "butterfly-knife-fade",
    weapon: "Butterfly Knife",
    name: "Fade",
    rarity: "special",
    image: "/assets/skins/butterfly-knife-fade.webp",
    skinId: "butterfly-knife-fade",
    value: 204328,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Butterfly Knife | Fade (Factory New)",
    marketplace: "Skinport",
    priceSource: "https://csgoskins.gg/items/butterfly-knife-fade",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "m9-bayonet-marble-fade",
    weapon: "M9 Bayonet",
    name: "Marble Fade",
    rarity: "special",
    image: "/assets/skins/m9-bayonet-marble-fade.webp",
    skinId: "m9-bayonet-marble-fade",
    value: 68670,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ M9 Bayonet | Marble Fade (Factory New)",
    marketplace: "SkinBaron",
    priceSource: "https://csgoskins.gg/items/m9-bayonet-marble-fade",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "talon-knife-tiger-tooth",
    weapon: "Talon Knife",
    name: "Tiger Tooth",
    rarity: "special",
    image: "/assets/skins/talon-knife-tiger-tooth.webp",
    skinId: "talon-knife-tiger-tooth",
    value: 41951,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Talon Knife | Tiger Tooth (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/talon-knife-tiger-tooth",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "huntsman-knife-slaughter",
    weapon: "Huntsman Knife",
    name: "Slaughter",
    rarity: "special",
    image: "/assets/skins/huntsman-knife-slaughter.webp",
    skinId: "huntsman-knife-slaughter",
    value: 23428,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Huntsman Knife | Slaughter (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/huntsman-knife-slaughter",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "sport-gloves-vice",
    weapon: "Sport Gloves",
    name: "Vice",
    rarity: "special",
    image: "/assets/skins/sport-gloves-vice.webp",
    skinId: "sport-gloves-vice",
    value: 550000,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Sport Gloves | Vice (Factory New)",
    marketplace: "CSFloat",
    priceSource: "https://csgoskins.gg/items/sport-gloves-vice",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "specialist-gloves-crimson-kimono",
    weapon: "Specialist Gloves",
    name: "Crimson Kimono",
    rarity: "special",
    image: "/assets/skins/specialist-gloves-crimson-kimono.webp",
    skinId: "specialist-gloves-crimson-kimono",
    value: 865090,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Specialist Gloves | Crimson Kimono (Factory New)",
    marketplace: "BUFF163",
    priceSource: "https://csgoskins.gg/items/specialist-gloves-crimson-kimono",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
  {
    id: "driver-gloves-king-snake",
    weapon: "Driver Gloves",
    name: "King Snake",
    rarity: "special",
    image: "/assets/skins/driver-gloves-king-snake.webp",
    skinId: "driver-gloves-king-snake",
    value: 211576,
    currency: "USD",
    wear: "Factory New",
    quality: "Normal",
    phase: null,
    marketHashName: "★ Driver Gloves | King Snake (Factory New)",
    marketplace: "SkinSwap",
    priceSource: "https://csgoskins.gg/items/driver-gloves-king-snake",
    priceCheckedAt: "2026-10-03T23:01:30Z",
    sourceAge: "today",
    wearShort: "FN",
  },
];
export const skinById = new Map(skins.map((skin) => [skin.id, skin]));
const caseDefinitions = [
  {
    id: "ember",
    name: "Разогрев",
    subtitle: "Первый шаг к большому дропу",
    color: "#ff873b",
    image: "/assets/cases/case-1.webp",
    drops: [
      {
        skinId: "ak-47-elite-build",
        weight: 8500,
      },
      {
        skinId: "ak-47-slate",
        weight: 1000,
      },
      {
        skinId: "desert-eagle-directive",
        weight: 350,
      },
      {
        skinId: "ak-47-redline",
        weight: 120,
      },
      {
        skinId: "huntsman-knife-slaughter",
        weight: 25,
      },
      {
        skinId: "ak-47-asiimov",
        weight: 5,
      },
    ],
  },
  {
    id: "toxic",
    name: "Токсик",
    subtitle: "Опасно яркий",
    color: "#b4ec42",
    image: "/assets/cases/case-2.webp",
    drops: [
      {
        skinId: "m4a4-magnesium",
        weight: 8500,
      },
      {
        skinId: "ak-47-phantom-disruptor",
        weight: 1000,
      },
      {
        skinId: "awp-atheris",
        weight: 350,
      },
      {
        skinId: "usp-s-cyrex",
        weight: 120,
      },
      {
        skinId: "awp-containment-breach",
        weight: 25,
      },
      {
        skinId: "m9-bayonet-marble-fade",
        weight: 5,
      },
    ],
  },
  {
    id: "frost",
    name: "Ледниковый",
    subtitle: "Холодный расчёт",
    color: "#68cdff",
    image: "/assets/cases/case-3.webp",
    drops: [
      {
        skinId: "ssg-08-abyss",
        weight: 8500,
      },
      {
        skinId: "m4a1-s-decimator",
        weight: 1000,
      },
      {
        skinId: "glock-18-water-elemental",
        weight: 350,
      },
      {
        skinId: "desert-eagle-printstream",
        weight: 120,
      },
      {
        skinId: "awp-asiimov",
        weight: 25,
      },
      {
        skinId: "driver-gloves-king-snake",
        weight: 5,
      },
    ],
  },
  {
    id: "neon",
    name: "Неон",
    subtitle: "Ночная смена",
    color: "#b381ff",
    image: "/assets/cases/case-4.webp",
    drops: [
      {
        skinId: "usp-s-ticket-to-hell",
        weight: 8500,
      },
      {
        skinId: "glock-18-vogue",
        weight: 1000,
      },
      {
        skinId: "m4a1-s-decimator",
        weight: 350,
      },
      {
        skinId: "ak-47-neon-rider",
        weight: 120,
      },
      {
        skinId: "m4a1-s-hyper-beast",
        weight: 25,
      },
      {
        skinId: "sport-gloves-vice",
        weight: 5,
      },
    ],
  },
  {
    id: "samurai",
    name: "Самурай",
    subtitle: "Один точный удар",
    color: "#ff5272",
    image: "/assets/cases/case-5.webp",
    drops: [
      {
        skinId: "m4a4-evil-daimyo",
        weight: 8500,
      },
      {
        skinId: "usp-s-cortex",
        weight: 1000,
      },
      {
        skinId: "ak-47-redline",
        weight: 350,
      },
      {
        skinId: "usp-s-kill-confirmed",
        weight: 120,
      },
      {
        skinId: "ak-47-fire-serpent",
        weight: 25,
      },
      {
        skinId: "karambit-doppler-ruby",
        weight: 5,
      },
    ],
  },
  {
    id: "royal",
    name: "Королевский",
    subtitle: "Для тех, кто любит золото",
    color: "#edca62",
    image: "/assets/cases/case-6.webp",
    drops: [
      {
        skinId: "ak-47-slate",
        weight: 8800,
      },
      {
        skinId: "ak-47-phantom-disruptor",
        weight: 1000,
      },
      {
        skinId: "awp-asiimov",
        weight: 150,
      },
      {
        skinId: "talon-knife-tiger-tooth",
        weight: 40,
      },
      {
        skinId: "desert-eagle-blaze",
        weight: 9,
      },
      {
        skinId: "awp-dragon-lore",
        weight: 1,
      },
    ],
  },
  {
    id: "ghost",
    name: "Призрак",
    subtitle: "Появляется из ниоткуда",
    color: "#c1d2e3",
    image: "/assets/cases/case-7.webp",
    drops: [
      {
        skinId: "usp-s-cyrex",
        weight: 8500,
      },
      {
        skinId: "m4a1-s-decimator",
        weight: 1000,
      },
      {
        skinId: "desert-eagle-printstream",
        weight: 350,
      },
      {
        skinId: "awp-hyper-beast",
        weight: 120,
      },
      {
        skinId: "butterfly-knife-fade",
        weight: 25,
      },
      {
        skinId: "driver-gloves-king-snake",
        weight: 5,
      },
    ],
  },
  {
    id: "inferno",
    name: "Инферно",
    subtitle: "Температура на максимуме",
    color: "#ff5f3a",
    image: "/assets/cases/case-8.webp",
    drops: [
      {
        skinId: "p250-nevermore",
        weight: 8500,
      },
      {
        skinId: "usp-s-kill-confirmed",
        weight: 1000,
      },
      {
        skinId: "ak-47-asiimov",
        weight: 350,
      },
      {
        skinId: "ak-47-fire-serpent",
        weight: 120,
      },
      {
        skinId: "m4a4-howl",
        weight: 25,
      },
      {
        skinId: "specialist-gloves-crimson-kimono",
        weight: 5,
      },
    ],
  },
  {
    id: "cosmos",
    name: "Космос",
    subtitle: "За пределами обычного",
    color: "#698aff",
    image: "/assets/cases/case-9.webp",
    drops: [
      {
        skinId: "ak-47-neon-rider",
        weight: 8800,
      },
      {
        skinId: "awp-containment-breach",
        weight: 1000,
      },
      {
        skinId: "m9-bayonet-marble-fade",
        weight: 150,
      },
      {
        skinId: "sport-gloves-vice",
        weight: 40,
      },
      {
        skinId: "karambit-doppler-ruby",
        weight: 9,
      },
      {
        skinId: "awp-dragon-lore",
        weight: 1,
      },
    ],
  },
  {
    id: "diamond",
    name: "Чёрный бриллиант",
    subtitle: "Только особые предметы",
    color: "#e2c477",
    image: "/assets/cases/case-10.webp",
    drops: [
      {
        skinId: "huntsman-knife-slaughter",
        weight: 8800,
      },
      {
        skinId: "talon-knife-tiger-tooth",
        weight: 1000,
      },
      {
        skinId: "m9-bayonet-marble-fade",
        weight: 150,
      },
      {
        skinId: "butterfly-knife-fade",
        weight: 40,
      },
      {
        skinId: "driver-gloves-king-snake",
        weight: 9,
      },
      {
        skinId: "karambit-doppler-ruby",
        weight: 1,
      },
    ],
  },
];
export const cases = caseDefinitions.map((item) => ({
  ...item,
  ...priceCase(
    item.drops,
    skinById,
    item.drops.map((drop) => drop.weight),
  ),
}));
export const caseById = new Map(cases.map((item) => [item.id, item]));
export const rarities = {
  milspec: { name: "Армейское", color: "#659cff" },
  restricted: { name: "Запрещённое", color: "#ae7dff" },
  classified: { name: "Засекреченное", color: "#e374e4" },
  covert: { name: "Тайное", color: "#ff646d" },
  special: { name: "Особое", color: "#f0c765" },
  contraband: { name: "Контрабанда", color: "#eea35b" },
};
